/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import com.jtattoo.plaf.luna.LunaLookAndFeel;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.synth.SynthLookAndFeel;
import listaenlazada.Listas;
import listaenlazada.Nodo;

/**
 *
 * @author 59396
 */
public class operacionesNodo extends javax.swing.JFrame {
    Listas l = new Listas();

    /**
     * Creates new form operacionesNodo
     */
    public operacionesNodo() {
        initComponents();
        this.getContentPane().setBackground(new Color(74, 79, 84));
        btbBuscar.setVisible(false);
        txtBuscar.setVisible(false);
        btbModifcar.setVisible(false);
        txtModificarNuevo.setVisible(false);
        txtModificarAntiguo.setVisible(false);
        btbEliminar.setVisible(false);
        txtEliminar.setVisible(false);
        labBuscar.setVisible(false);
        labModificarNuevo.setVisible(false);
        labModificarAntiguo.setVisible(false);
        labEliminar.setVisible(false);
        //txtInsertar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEliminar = new javax.swing.JTextField();
        btbinsertar = new javax.swing.JButton();
        btbMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlista = new javax.swing.JTextArea();
        btbvaciar = new javax.swing.JButton();
        btbBuscar = new javax.swing.JButton();
        btbModifcar = new javax.swing.JButton();
        txtModificarNuevo = new javax.swing.JTextField();
        btbEliminar = new javax.swing.JButton();
        txtModificarAntiguo = new javax.swing.JTextField();
        txtInsertar = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        labBuscar = new javax.swing.JLabel();
        labModificarNuevo = new javax.swing.JLabel();
        labModificarAntiguo = new javax.swing.JLabel();
        labEliminar = new javax.swing.JLabel();
        btbvaciarTodo = new javax.swing.JButton();
        btbSalir = new javax.swing.JButton();
        labinsertar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operaciones con nodos");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Operaciones con nodos ");

        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });
        txtEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEliminarKeyTyped(evt);
            }
        });

        btbinsertar.setBackground(new java.awt.Color(0, 153, 153));
        btbinsertar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbinsertar.setText("Insertar NODO");
        btbinsertar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbinsertarActionPerformed(evt);
            }
        });

        btbMostrar.setBackground(new java.awt.Color(0, 153, 153));
        btbMostrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbMostrar.setText("Mostrar NODO");
        btbMostrar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbMostrarActionPerformed(evt);
            }
        });

        txtAlista.setColumns(20);
        txtAlista.setRows(5);
        jScrollPane1.setViewportView(txtAlista);

        btbvaciar.setBackground(new java.awt.Color(0, 153, 153));
        btbvaciar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbvaciar.setText("Vaciar Campos ");
        btbvaciar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbvaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbvaciarActionPerformed(evt);
            }
        });

        btbBuscar.setBackground(new java.awt.Color(0, 153, 153));
        btbBuscar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbBuscar.setText("Buscarlo");
        btbBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBuscarActionPerformed(evt);
            }
        });

        btbModifcar.setBackground(new java.awt.Color(0, 153, 153));
        btbModifcar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbModifcar.setText("Modificarlo");
        btbModifcar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbModifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbModifcarActionPerformed(evt);
            }
        });

        txtModificarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarNuevoActionPerformed(evt);
            }
        });
        txtModificarNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificarNuevoKeyTyped(evt);
            }
        });

        btbEliminar.setBackground(new java.awt.Color(0, 153, 153));
        btbEliminar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbEliminar.setText("Eliminarlo");
        btbEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbEliminarActionPerformed(evt);
            }
        });

        txtModificarAntiguo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificarAntiguoKeyTyped(evt);
            }
        });

        txtInsertar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInsertarKeyTyped(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        bBuscar.setBackground(new java.awt.Color(0, 153, 153));
        bBuscar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bBuscar.setText("Buscar NODO");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bModificar.setBackground(new java.awt.Color(0, 153, 153));
        bModificar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bModificar.setText("Modificar NODO");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setBackground(new java.awt.Color(0, 153, 153));
        bEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bEliminar.setText("Eliminar NODO");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        labBuscar.setBackground(new java.awt.Color(255, 255, 255));
        labBuscar.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        labBuscar.setForeground(new java.awt.Color(0, 204, 204));
        labBuscar.setText("Insertar Nodo a buscar ");

        labModificarNuevo.setBackground(new java.awt.Color(255, 255, 255));
        labModificarNuevo.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        labModificarNuevo.setForeground(new java.awt.Color(0, 204, 204));
        labModificarNuevo.setText("Nodo nuevo");

        labModificarAntiguo.setBackground(new java.awt.Color(255, 255, 255));
        labModificarAntiguo.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        labModificarAntiguo.setForeground(new java.awt.Color(0, 204, 204));
        labModificarAntiguo.setText("Nodo a cambiar");

        labEliminar.setBackground(new java.awt.Color(255, 255, 255));
        labEliminar.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        labEliminar.setForeground(new java.awt.Color(0, 204, 204));
        labEliminar.setText("Nodo a eliminar");

        btbvaciarTodo.setBackground(new java.awt.Color(0, 153, 153));
        btbvaciarTodo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbvaciarTodo.setText("Resetear botonones");
        btbvaciarTodo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbvaciarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbvaciarTodoActionPerformed(evt);
            }
        });

        btbSalir.setBackground(new java.awt.Color(255, 51, 51));
        btbSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbSalir.setText("Salir");
        btbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSalirActionPerformed(evt);
            }
        });

        labinsertar.setBackground(new java.awt.Color(255, 255, 255));
        labinsertar.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        labinsertar.setForeground(new java.awt.Color(0, 204, 204));
        labinsertar.setText("Insertar Nodo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btbinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btbMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btbvaciar, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(bBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtModificarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtModificarAntiguo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labModificarAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labModificarNuevo)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btbModifcar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labBuscar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(bModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btbvaciarTodo)
                        .addGap(26, 26, 26)
                        .addComponent(btbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labinsertar)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbvaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btbBuscar))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbModifcar)
                            .addComponent(txtModificarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificarAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labModificarNuevo))
                    .addComponent(labModificarAntiguo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbvaciarTodo)
                    .addComponent(btbSalir))
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEliminarKeyTyped
        char c = evt.getKeyChar();
        String txt = txtEliminar.getText();
            if(!(Character.isDigit(c)) || txt.length() >= 3 || (txt.isEmpty() && c == '0')){
                evt.consume();
        }
    }//GEN-LAST:event_txtEliminarKeyTyped

    private void btbinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbinsertarActionPerformed
        String valortxt = txtInsertar.getText();
        if(!valortxt.isEmpty() && valortxt.matches("\\d+")){
        int valor = Integer.parseInt(valortxt);
        l.insertarNodoOrdenado(valor);
        JOptionPane.showMessageDialog(null, "Valor ingresado : "+valortxt);
        }else{
            JOptionPane.showMessageDialog(null, "No debe de estar vacio ingrese un nodo por favor");
        }
        txtInsertar.setText("");
    }//GEN-LAST:event_btbinsertarActionPerformed

    private void btbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbMostrarActionPerformed
    if (!l.verLista()) {
        txtAlista.append("\nNodos: " + l.imprimirLista());
    } else {
        JOptionPane.showMessageDialog(null, "La lista está vacía");
    }

    txtEliminar.setText("");
    }//GEN-LAST:event_btbMostrarActionPerformed

    private void btbvaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbvaciarActionPerformed
        // TODO add your handling code here:
        txtAlista.setText(" ");
        txtEliminar.setText(null);
        txtModificarNuevo.setText(null);
        txtBuscar.setText(null);
        txtInsertar.setText(null);
        txtModificarAntiguo.setText(null);     
    }//GEN-LAST:event_btbvaciarActionPerformed

    private void btbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBuscarActionPerformed
    String valortxt = txtBuscar.getText();
    if (!valortxt.isEmpty() && valortxt.matches("\\d+")) {
        int valor = Integer.parseInt(valortxt);
        Nodo no = l.buscarNodo(valor);
        if (no != null) {
            // El nodo fue encontrado, realiza la acción deseada
            JOptionPane.showMessageDialog(null,"Encontrado : " +no.dato); //Lo hacia con esto pero mas practico es la linea siguiente
            txtAlista.append("\nValor encontrado : "+valortxt);
        } else {
            // El nodo no fue encontrado
            JOptionPane.showMessageDialog(null, "Valor no encontrado :(");
        }
    } else {
        // El valor ingresado no es un número válido
        JOptionPane.showMessageDialog(null, "Debe ingresar un numero a buscar");
    }
    txtBuscar.setText("");
    }//GEN-LAST:event_btbBuscarActionPerformed

    private void txtModificarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarNuevoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtModificarNuevoActionPerformed

    private void btbModifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbModifcarActionPerformed
    String valortxt = txtModificarNuevo.getText();
    String valorsito = txtModificarAntiguo.getText();
    
    if (!valortxt.isEmpty() && valortxt.matches("\\d+")) {
        int valorBuscado = Integer.parseInt(valortxt);
        String nuevoValorTxt = txtModificarAntiguo.getText();
        
        if (!nuevoValorTxt.isEmpty() && nuevoValorTxt.matches("\\d+")) {
            int nuevoValor = Integer.parseInt(nuevoValorTxt);
            
            // Call the modificarNodo method and check if the node was modified
            boolean nodoModificado = l.modificarNodo(valorBuscado, nuevoValor);
            
            if (nodoModificado) {
                // The node was found and modified, append the modification message to txtAlista
                JOptionPane.showMessageDialog(null, "Nodo modificado "+valorBuscado+" --> "+valorsito);
                txtAlista.append("\nValor : " + valortxt + " Modificado por : " + valorsito);
            } else {
                // The node was not found
                JOptionPane.showMessageDialog(null, "Nodo no encontrado");
            }
        } else {
            // The new value entered is not a valid number
            JOptionPane.showMessageDialog(null, "Se debe ingresar un número");
        }
    }
    
    txtEliminar.setText("");
    txtModificarNuevo.setText("");
    txtModificarAntiguo.setText("");

    }//GEN-LAST:event_btbModifcarActionPerformed

    private void btbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbEliminarActionPerformed
    String valortxt = txtEliminar.getText();
    if (!valortxt.isEmpty() && valortxt.matches("\\d+")) {
        int valor = Integer.parseInt(valortxt);
        
        boolean nodoEliminado = l.eliminarNodo(valor);
        
        if (nodoEliminado) {
            // El nodo fue eliminado exitosamente
            txtAlista.append("\nEliminado: " + valortxt);
        } else {
            // El nodo no fue encontrado
            JOptionPane.showMessageDialog(null, "Nodo no encontrado");
        }
    } else {
        JOptionPane.showMessageDialog(null, "No debe estar vacío y debe ser un número válido");
    }
    
    txtEliminar.setText("");
    }//GEN-LAST:event_btbEliminarActionPerformed

    private void txtModificarAntiguoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarAntiguoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String txt = txtModificarAntiguo.getText();
            if(!(Character.isDigit(c)) || txt.length() >= 3 || (txt.isEmpty() && c == '0')){
                evt.consume();
        }
    }//GEN-LAST:event_txtModificarAntiguoKeyTyped

    private void txtInsertarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInsertarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String txt = txtInsertar.getText();
            if(!(Character.isDigit(c)) || txt.length() >= 3 || (txt.isEmpty() && c == '0')){
                evt.consume();
        }
    }//GEN-LAST:event_txtInsertarKeyTyped

    private void txtModificarNuevoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarNuevoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String txt = txtModificarNuevo.getText();
            if(!(Character.isDigit(c)) || txt.length() >= 3 || (txt.isEmpty() && c == '0')){
                evt.consume();
        }
    }//GEN-LAST:event_txtModificarNuevoKeyTyped

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String txt = txtBuscar.getText();
            if(!(Character.isDigit(c)) || txt.length() >= 3 || (txt.isEmpty() && c == '0')){
                evt.consume();
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        btbBuscar.setVisible(true);
        txtBuscar.setVisible(true);
        labBuscar.setVisible(true);
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
        btbModifcar.setVisible(true);
        txtModificarNuevo.setVisible(true);
        txtModificarAntiguo.setVisible(true);
        labModificarNuevo.setVisible(true);
        labModificarAntiguo.setVisible(true);
    }//GEN-LAST:event_bModificarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        btbEliminar.setVisible(true);
        txtEliminar.setVisible(true);
        labEliminar.setVisible(true);
    }//GEN-LAST:event_bEliminarActionPerformed

    private void btbvaciarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbvaciarTodoActionPerformed
        // TODO add your handling code here:
        //Vacia los campos existentes en los JtextField
        
        txtAlista.setText(" ");
        txtEliminar.setText(null);
        txtModificarNuevo.setText(null);
        txtBuscar.setText(null);
        txtInsertar.setText(null);
        txtModificarAntiguo.setText(null);   
        //Al vacia se eliminan los botones de  buscar modificar y eliminar ademas de los otros compnentes relacionados   
        btbBuscar.setVisible(false);
        txtBuscar.setVisible(false);
        labBuscar.setVisible(false);
        btbModifcar.setVisible(false);
        txtModificarNuevo.setVisible(false);
        txtModificarAntiguo.setVisible(false);
        labModificarNuevo.setVisible(false);
        labModificarAntiguo.setVisible(false);
        btbEliminar.setVisible(false);
        txtEliminar.setVisible(false);
        labEliminar.setVisible(false);
    }//GEN-LAST:event_btbvaciarTodoActionPerformed

    private void btbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSalirActionPerformed
        // TODO add your handling code here:
    int respuesta = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres salir?", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
    if (respuesta == JOptionPane.YES_OPTION) {
        // Cerrar la ventana
        dispose();
    }
    }//GEN-LAST:event_btbSalirActionPerformed

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operacionesNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operacionesNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operacionesNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operacionesNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                try {
//                    UIManager.setLookAndFeel(new TextureLookAndFeel());
//                } catch (UnsupportedLookAndFeelException ex) {
//                    Logger.getLogger(operacionesNodo.class.getName()).log(Level.SEVERE, null, ex);
//                }
                
                new operacionesNodo().setVisible(true);             
         }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton btbBuscar;
    private javax.swing.JButton btbEliminar;
    private javax.swing.JButton btbModifcar;
    private javax.swing.JButton btbMostrar;
    private javax.swing.JButton btbSalir;
    private javax.swing.JButton btbinsertar;
    private javax.swing.JButton btbvaciar;
    private javax.swing.JButton btbvaciarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labBuscar;
    private javax.swing.JLabel labEliminar;
    private javax.swing.JLabel labModificarAntiguo;
    private javax.swing.JLabel labModificarNuevo;
    private javax.swing.JLabel labinsertar;
    private javax.swing.JTextArea txtAlista;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtInsertar;
    private javax.swing.JTextField txtModificarAntiguo;
    private javax.swing.JTextField txtModificarNuevo;
    // End of variables declaration//GEN-END:variables
}
