/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import cola.Colas;
import cola.Nodo;
import javax.swing.JOptionPane;

/**
 *
 * @author 59396
 */
public class operacionesCola extends javax.swing.JFrame {
    Colas c = new Colas();
    /**
     * Creates new form operacionesCola
     */
    public operacionesCola() {
        initComponents();
        txtBuscar.setVisible(false);
        labBuscar.setVisible(false);
        btbBuscar.setVisible(false);
        txtModificarAntiguo.setVisible(false);
        txtModificarNuevo.setVisible(false);
        labModificarAntiguo.setVisible(false);
        labModificarNuevo.setVisible(false);
        btbModifcar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btbvaciarTodo = new javax.swing.JButton();
        btbModifcar = new javax.swing.JButton();
        txtModificarAntiguo = new javax.swing.JTextField();
        labBuscar = new javax.swing.JLabel();
        btbSalir = new javax.swing.JButton();
        labModificarAntiguo = new javax.swing.JLabel();
        txtInsertar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlista = new javax.swing.JTextArea();
        txtBuscar = new javax.swing.JTextField();
        btbvaciar = new javax.swing.JButton();
        btbinsertar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        labinsertar = new javax.swing.JLabel();
        btbMostrar = new javax.swing.JButton();
        btbBuscar = new javax.swing.JButton();
        txtModificarNuevo = new javax.swing.JTextField();
        bModificar = new javax.swing.JButton();
        labModificarNuevo = new javax.swing.JLabel();
        btbEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btbvaciarTodo.setBackground(new java.awt.Color(102, 102, 102));
        btbvaciarTodo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbvaciarTodo.setText("Resetear botonones");
        btbvaciarTodo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbvaciarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbvaciarTodoActionPerformed(evt);
            }
        });

        btbModifcar.setBackground(new java.awt.Color(102, 102, 102));
        btbModifcar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbModifcar.setText("Modificarlo");
        btbModifcar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbModifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbModifcarActionPerformed(evt);
            }
        });

        txtModificarAntiguo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificarAntiguoKeyTyped(evt);
            }
        });

        labBuscar.setBackground(new java.awt.Color(255, 255, 255));
        labBuscar.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        labBuscar.setText("Insertar Nodo a buscar ");

        btbSalir.setBackground(new java.awt.Color(255, 51, 51));
        btbSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbSalir.setText("Salir");
        btbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSalirActionPerformed(evt);
            }
        });

        labModificarAntiguo.setBackground(new java.awt.Color(255, 255, 255));
        labModificarAntiguo.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        labModificarAntiguo.setText("Nodo a cambiar");

        txtInsertar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInsertarKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Operaciones con nodos Cola");

        txtAlista.setColumns(20);
        txtAlista.setRows(5);
        jScrollPane1.setViewportView(txtAlista);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btbvaciar.setBackground(new java.awt.Color(102, 102, 102));
        btbvaciar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbvaciar.setText("Vaciar Campos ");
        btbvaciar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbvaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbvaciarActionPerformed(evt);
            }
        });

        btbinsertar.setBackground(new java.awt.Color(102, 102, 102));
        btbinsertar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbinsertar.setText("Insertar NODO");
        btbinsertar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbinsertarActionPerformed(evt);
            }
        });

        bBuscar.setBackground(new java.awt.Color(102, 102, 102));
        bBuscar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bBuscar.setText("Buscar NODO");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        labinsertar.setBackground(new java.awt.Color(255, 255, 255));
        labinsertar.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        labinsertar.setText("Insertar Nodo");

        btbMostrar.setBackground(new java.awt.Color(102, 102, 102));
        btbMostrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbMostrar.setText("Mostrar NODO");
        btbMostrar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbMostrarActionPerformed(evt);
            }
        });

        btbBuscar.setBackground(new java.awt.Color(102, 102, 102));
        btbBuscar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbBuscar.setText("Buscarlo");
        btbBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBuscarActionPerformed(evt);
            }
        });

        txtModificarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarNuevoActionPerformed(evt);
            }
        });
        txtModificarNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificarNuevoKeyTyped(evt);
            }
        });

        bModificar.setBackground(new java.awt.Color(102, 102, 102));
        bModificar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bModificar.setText("Modificar NODO");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        labModificarNuevo.setBackground(new java.awt.Color(255, 255, 255));
        labModificarNuevo.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        labModificarNuevo.setText("Nodo nuevo");

        btbEliminar.setBackground(new java.awt.Color(102, 102, 102));
        btbEliminar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btbEliminar.setText("Eliminarlo");
        btbEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btbinsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btbMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btbvaciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labBuscar))
                                        .addGap(20, 20, 20)
                                        .addComponent(btbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtModificarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtModificarAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btbModifcar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labModificarAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labModificarNuevo)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(bModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(btbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btbvaciarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btbinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btbMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labinsertar)
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btbvaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbModifcar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificarAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labModificarNuevo))
                    .addComponent(labModificarAntiguo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbvaciarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbvaciarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbvaciarTodoActionPerformed
        // TODO add your handling code here:
        //Vacia los campos existentes en los JtextField

        txtAlista.setText(" ");
        txtModificarNuevo.setText(null);
        txtBuscar.setText(null);
        txtInsertar.setText(null);
        txtModificarAntiguo.setText(null);
        //Al vacia se eliminan los botones de  buscar modificar y eliminar ademas de los otros compnentes relacionados
        btbBuscar.setVisible(false);
        txtBuscar.setVisible(false);
        labBuscar.setVisible(false);
        btbModifcar.setVisible(false);
        txtModificarNuevo.setVisible(false);
        txtModificarAntiguo.setVisible(false);
        labModificarNuevo.setVisible(false);
        labModificarAntiguo.setVisible(false);
        btbEliminar.setVisible(false);
    }//GEN-LAST:event_btbvaciarTodoActionPerformed

    private void btbModifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbModifcarActionPerformed
        String valortxt = txtModificarNuevo.getText();
        String valorsito = txtModificarAntiguo.getText();

        if (!valortxt.isEmpty() && valortxt.matches("\\d+")) {
            int valorBuscado = Integer.parseInt(valortxt);
            String nuevoValorTxt = txtModificarAntiguo.getText();

            if (!nuevoValorTxt.isEmpty() && nuevoValorTxt.matches("\\d+")) {
                int nuevoValor = Integer.parseInt(nuevoValorTxt);

                // Call the modificarNodo method and check if the node was modified
                boolean nodoModificado = c.modificarNodoCola(valorBuscado, nuevoValor);
                if (nodoModificado) {
                    // The node was found and modified, append the modification message to txtAlista
                    JOptionPane.showMessageDialog(null, "Nodo modificado " + valorBuscado + " --> " + valorsito);
                    txtAlista.append("\nValor : " + valortxt + " Modificado por : " + valorsito);
                } else {
                    // The node was not found
                    JOptionPane.showMessageDialog(null, "Nodo no encontrado");
                }
            } else {
                // The new value entered is not a valid number
                JOptionPane.showMessageDialog(null, "Se debe ingresar un número");
            }
        }

        txtModificarNuevo.setText("");
        txtModificarAntiguo.setText("");
    }//GEN-LAST:event_btbModifcarActionPerformed

    private void txtModificarAntiguoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarAntiguoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String txt = txtModificarAntiguo.getText();
        if (!(Character.isDigit(c)) || txt.length() >= 3 || (txt.isEmpty() && c == '0')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtModificarAntiguoKeyTyped

    private void btbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres salir?", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            // Cerrar la ventana
            dispose();
        }
    }//GEN-LAST:event_btbSalirActionPerformed

    private void txtInsertarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInsertarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String txt = txtInsertar.getText();
        if (!(Character.isDigit(c)) || txt.length() >= 3 || (txt.isEmpty() && c == '0')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtInsertarKeyTyped

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String txt = txtBuscar.getText();
        if (!(Character.isDigit(c)) || txt.length() >= 3 || (txt.isEmpty() && c == '0')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btbvaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbvaciarActionPerformed
        // TODO add your handling code here:
        txtAlista.setText(" ");
        txtModificarNuevo.setText(null);
        txtBuscar.setText(null);
        txtInsertar.setText(null);
        txtModificarAntiguo.setText(null);
    }//GEN-LAST:event_btbvaciarActionPerformed

    private void btbinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbinsertarActionPerformed
        String valortxt = txtInsertar.getText();
        if (!valortxt.isEmpty() && valortxt.matches("\\d+")) {
            int valor = Integer.parseInt(valortxt);
            c.encolar(valor);
            JOptionPane.showMessageDialog(null, "Valor ingresado : " + valortxt);
            txtAlista.append("\nIngresado : " + valortxt);
        } else {
            JOptionPane.showMessageDialog(null, "No debe de estar vacio ingrese un nodo por favor");
        }

        txtInsertar.setText("");
    }//GEN-LAST:event_btbinsertarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        btbBuscar.setVisible(true);
        txtBuscar.setVisible(true);
        labBuscar.setVisible(true);
    }//GEN-LAST:event_bBuscarActionPerformed

    private void btbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbMostrarActionPerformed
        if (!c.verCola()) {
            txtAlista.append("\nNodos : " + c.imprimirCola());
        } else {
            JOptionPane.showMessageDialog(null, "La lista está vacía");
        }


    }//GEN-LAST:event_btbMostrarActionPerformed

    private void btbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBuscarActionPerformed
        String valortxt = txtBuscar.getText();
        if (!valortxt.isEmpty() && valortxt.matches("\\d+")) {
            int valor = Integer.parseInt(valortxt);
            Nodo no = c.buscarNodoCola(valor);
            if (no != null) {
                // El nodo fue encontrado, realiza la acción deseada
                JOptionPane.showMessageDialog(null, "Encontrado : " + no.dato); //Lo hacia con esto pero mas practico es la linea siguiente
                txtAlista.append("\nValor encontrado : " + valortxt);
            } else {
                // El nodo no fue encontrado
                JOptionPane.showMessageDialog(null, "Valor no encontrado :(");
            }
        } else {
            // El valor ingresado no es un número válido
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero a buscar");
        }
        txtBuscar.setText("");
    }//GEN-LAST:event_btbBuscarActionPerformed

    private void txtModificarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarNuevoActionPerformed

    private void txtModificarNuevoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarNuevoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String txt = txtModificarNuevo.getText();
        if (!(Character.isDigit(c)) || txt.length() >= 3 || (txt.isEmpty() && c == '0')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtModificarNuevoKeyTyped

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
        btbModifcar.setVisible(true);
        txtModificarNuevo.setVisible(true);
        txtModificarAntiguo.setVisible(true);
        labModificarNuevo.setVisible(true);
        labModificarAntiguo.setVisible(true);
    }//GEN-LAST:event_bModificarActionPerformed

    private void btbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbEliminarActionPerformed
    boolean nodoEliminado = c.eliminarNodoCola();
    Nodo nodoFrente = c.cola.peek();
    int numeroEliminado = nodoFrente.dato;

    if (nodoEliminado) {
        // El nodo fue eliminado exitosamente
        txtAlista.append("\nEliminado: " +numeroEliminado);
    } else {
        // La cola está vacía
        JOptionPane.showMessageDialog(null, "La cola está vacía, no se puede eliminar");
    }
    }//GEN-LAST:event_btbEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operacionesCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operacionesCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operacionesCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operacionesCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operacionesCola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton btbBuscar;
    private javax.swing.JButton btbEliminar;
    private javax.swing.JButton btbModifcar;
    private javax.swing.JButton btbMostrar;
    private javax.swing.JButton btbSalir;
    private javax.swing.JButton btbinsertar;
    private javax.swing.JButton btbvaciar;
    private javax.swing.JButton btbvaciarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labBuscar;
    private javax.swing.JLabel labModificarAntiguo;
    private javax.swing.JLabel labModificarNuevo;
    private javax.swing.JLabel labinsertar;
    private javax.swing.JTextArea txtAlista;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtInsertar;
    private javax.swing.JTextField txtModificarAntiguo;
    private javax.swing.JTextField txtModificarNuevo;
    // End of variables declaration//GEN-END:variables
}
